service: alg-serverless
frameworkVersion: '3'
useDotenv: true

custom:
  serverless-dynamodb:
    start:
      port: 8000
      docker: false
  dynamodb:
    stages:
      - local
    start:
      port: 7000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      convertEmptyValues: true
  prune:
    automatic: true
    number: 1

provider:
  name: aws
  environment:
    STAGE: ${opt:stage, 'dev'}
    API_BASE: ${env:API_BASE, 'sls'}
    NO_SIG_CHECK: ${env:NO_SIG_CHECK, '0'}
    BACKEND_PUBLIC_KEY: ${env:BACKEND_PUBLIC_KEY}
    TABLE_FORUM: alg-sls-${opt:stage, 'dev'}-forum
    TABLE_NOTIFICATIONS: alg-sls-${opt:stage, 'dev'}-notifications
    TABLE_CONNECTIONS: alg-sls-${opt:stage, 'dev'}-connections
    TABLE_STATS: alg-sls-${opt:stage, 'dev'}-stats
    TABLE_ACTIVE_USERS: alg-sls-${opt:stage, 'dev'}-active-users
    TABLE_USER_TASK_ACTIVITIES: alg-sls-${opt:stage, 'dev'}-user-task-activities
    APIGW_ENDPOINT: ${env:APIGW_ENDPOINT}
  runtime: nodejs20.x
  deploymentMethod: direct
  deploymentBucket:
    name: ${env:OPS_BUCKET}
  region: eu-west-3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"
        - Effect: Allow
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:BatchWriteItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:PartiQL*"
          Resource:
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-forum"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-notifications"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-connections"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-connections/index/*"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-stats"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-active-users"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-active-users/index/*"
            - !Sub "arn:aws:dynamodb:eu-west-3:${AWS::AccountId}:table/alg-sls-${opt:stage, 'dev'}-user-task-activities"
functions:

  server:
    handler: src/handlers.globalHandler
    description: ${param:description, 'Algorea Serverless Function'}
    # events: To be configured by hand to support using lambda aliases for ops
    #   - websocket:
    #       route: $connect
    #   - websocket:
    #       route: $disconnect
    #   - websocket:
    #       route: $default
    #   - ALB

package:
  individually: true
  patterns:
    - 'config.json'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline
  - serverless-prune-plugin

resources:
  Resources:
    NotificationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alg-sls-${opt:stage, 'dev'}-notifications
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: creationTime
            AttributeType: "N"
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: creationTime
            KeyType: RANGE
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alg-sls-${opt:stage, 'dev'}-connections
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: liveActivityPk
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: user-connections
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: connectionId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: live-activity-subscribers
            KeySchema:
              - AttributeName: liveActivityPk
                KeyType: HASH
              - AttributeName: connectionId
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
    ForumTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alg-sls-${opt:stage, 'dev'}-forum
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: "N"
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
    StatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alg-sls-${opt:stage, 'dev'}-stats
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: "N"
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
    ActiveUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alg-sls-${opt:stage, 'dev'}-active-users
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: gsiPk
            AttributeType: S
          - AttributeName: lastConnectedTime
            AttributeType: "N"
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: by-time
            KeySchema:
              - AttributeName: gsiPk
                KeyType: HASH
              - AttributeName: lastConnectedTime
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
    UserTaskActivitiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alg-sls-${opt:stage, 'dev'}-user-task-activities
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: time
            AttributeType: "N"
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
