AWSTemplateFormatVersion: "2010-09-09"
Description: The AWS CloudFormation template for alorea serverless
Resources:
  ForumTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: alg-serverless-fioi-..
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: time
          AttributeType: "N"
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: ts
          KeyType: RANGE
Outputs: {}